sudo: required
dist: trusty
language: node_js
node_js:
  - "6.9.1"
  - "6.10.0"
  - "7.2.0"
services:
  - mongodb
addons:
  srcclr: true
cache:
  directories:
  - node_modules
git:
  depth: 3
before_install:
  - pip install --user codecov
before_script:
  - npm prune
after_script:
  - npm run report-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 087a512f-6e23-4b5b-83a1-dc36b9e9986a