sudo: required
language: node_js
node_js:
  - "4.5.0"
  - "6.9.1"
  - "7.0.0"
services:
  - mongodb
env:
  - CXX=g++-5.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5.1
      - libboost-filesystem
cache:
  directories:
  - node_modules
git:
  depth: 3
before_script:
  - npm prune
after_script:
  - npm run report-coverage
